# Generated by Django 5.1.3 on 2025-01-13 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_remove_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='available',
        ),
    ]
