# Generated by Django 5.1.3 on 2024-12-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_payment_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='student',
            new_name='students',
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
